### ISSUE TITLE
new feature request:  working on an open curve and layer

### ISSUE THREAD

**Issue by pppalain** [pppalain/blendercam#101]
A user requested:

Is it possible, to cut like in two directions, like go z-3, cut to the end of path, in the end go to z-6 and cut i reverse directions - without going back in air and cutting from the starting point?

**Comment by PumpkinPai** [comment]
That is the behavior I get when I set up an svg and use the Cutout or Curve to Path strategy.  You would place the svg at the final depth within the CAM_machine object.  Enter "3mm" for the value of "Use Layers" in the Cam Operation Area panel.

**Comment by abosafia** [comment]
Yes it is possible. Use first down with meander
