### ISSUE TITLE
Blendercam does not deal with scaled models

### ISSUE THREAD

**Issue by migo1001** [pppalain/blendercam#104]
If I scale a model up or down, blendercam will try to generate an operation based on the original size of the model. Right now, the solution is to apply all scale changes before generating the operation. There should be a way to take into account the scaling .

**Comment by pppalain** [comment]
more precicely, the user had scaled 0.001 and units in mm.. should have ben 1.0 and units in mm... a simple test for that and message in info could help the situation

**Comment by eastshores** [comment]
Was this the global scale? I tried to replicate this issue with a mesh plane by setting the scale to 1.123 adding the operation, calculating, and then changing the scale to .5 but the operation successfully updated to reflect the scale value for the plane on the next calculate.

**Comment by abosafia** [comment]
In my side it is working perfect.
