### ISSUE TITLE
why when my project's the Add-on's upgrade version, then has different cam path.

### ISSUE THREAD

**Issue by TechD-Robin** [pppalain/blendercam#161]
when my project upgraded to version 1.0.1, the cam path like this :
![screenshot 1 0 1](https://github.com/pppalain/blendercam/assets/10447778/200e3c30-22a4-4a2e-a9e2-6366f148fb82)

after upgraded to version 1.0.2 or laters, like these:
![sceenshot 1 0 2](https://github.com/pppalain/blendercam/assets/10447778/06192e39-f370-4fd2-9e4d-0e1d2ab4e77a)
![screenshot 1 0 19](https://github.com/pppalain/blendercam/assets/10447778/8cc5b9fa-fa06-4d2a-996c-b44a47f08c49)

How can i fix properties in cam setting, let cam path like ver 1.0.1 ? 

----
Blender 4.1.1
BlenderCam Ver 1.0.1 to 1.0.2 ... 1.0.19

main cam operation setup :
3 axis, Profile(Cutout), Outside.

cam optimisation : use default setting. (without custom setting)

cam operation area : 
selected "Use Layers", 0.1 mm
free movement height 5mm
Set max depth from "Material"

cam cutter : 
Cutter : "End", diameter 0.6 mm, flutes 2.

**Comment by abosafia** [comment]
Try c_remove doubles.
In cam tools

**Comment by TechD-Robin** [comment]
> Try c_remove doubles. In cam tools

Thx for your help;

When i click the method first, the cam path like this:
![click first time result](https://github.com/pppalain/blendercam/assets/10447778/5aa17df4-0ee9-4e0d-b957-6b6760a848b6)

Then i try the method again, the cam path like before result on ver 1.0.1 :
![click 2nd time result](https://github.com/pppalain/blendercam/assets/10447778/16323db1-b311-4d8e-929a-63daf1c8e1ec)

If you know how working about the method "C-Remove doubles", maybe you can explain something, thank you.

**Comment by abosafia** [comment]
Curve remove doubles fixes the broken curve.
You can join us here https://riot.im/app/#/room/#blendercam:matrix.org
You can find help from great people.

**Comment by abosafia** [comment]
If you can upload the file before fixing the curve.
Thanks.

**Comment by TechD-Robin** [comment]
> If you can upload the file before fixing the curve. Thanks.
[Becky Words Scene.blend.zip](https://github.com/pppalain/blendercam/files/15105124/Becky.Words.Scene.blend.zip)

----
just removed unused object for these test, thx.

**Comment by abosafia** [comment]
Thanks for the file. It helped me improve the code. Wait for the update.
