### ISSUE TITLE
Calling operation "bpy.ops.curve.remove_double" error, could not be found

### ISSUE THREAD

**Issue by ydnatag** [pppalain/blendercam#166]
Hi! I really appreciate all the work you are doing with this project, I found blendercam the only mature and linux compatible CAM tool.

I installed blendercam, I had some issues with shapely (could not be installed in system packages, I created a venv with  `--system-site-packages` and used `blender -P venv/bin/pyhon`), Equations (with numpy==2.0.0, I solved it downgraded that to 1.2X and it works).

Now I have a issue, I selected a cube and clicked on "silhouete", having the following error:

```
Python: Traceback (most recent call last):
  File "/home/ademski/.config/blender/4.2/scripts/addons/blendercam-master/scripts/addons/cam/curvecamtools.py", line 815, in execute
    bpy.ops.object.curve_remove_doubles()
  File "/usr/share/blender/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/ademski/.config/blender/4.2/scripts/addons/blendercam-master/scripts/addons/cam/curvecamtools.py", line 595, in execute
    bpy.ops.curve.remove_double(distance=0.00001)
  File "/usr/share/blender/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.curve.remove_double" error, could not be found
Location: /usr/share/blender/4.2/scripts/modules/bpy/ops.py:109
```

I'm using blender 4.2.0 installed from arch repository.

Regards,
Andres

**Comment by pppalain** [comment]
I just just sent an update, let me verify

**Comment by pppalain** [comment]
so 4.2 has some changes which need the latest release.  some functionality may still be affected since some addons are now extentions and not available in python in the same way.  4.2 should have been version 5 in blender

**Comment by ydnatag** [comment]
Good to know that it wasn't me. I was not sure if installed it properly. 

Let me know when you push the fix for this and I can contribute with some testing

**Comment by pppalain** [comment]
in blender 4.2, you need to include the curve extra extensions.  the blendercam script can no longer enable them.

**Comment by ydnatag** [comment]
I installed it using the "get extensions" tab but blendercam is still not working. I will try to reproduce this in a docker environment because I don't know if it is something related to the python virtual environment i am using, a missing extension or a blendercam issue.

**Comment by ydnatag** [comment]
I reproduced the error using docker and linuxserver.io:

Steps to reproduce the bug:

* Clone and create config directory

```
git clone https://github.com/pppalain/blendercam.git
cd blendercam
mkdir blender_config
```

* Run blender in docker
```
docker run --rm --name blender -p 3000:3000 -p 3001:3001 -v $PWD:/blendercam -v ./blender_config:/config/ -e PUID=0 -e GUID=0 lscr.io/linuxserver/blender:latest
```
* Open blender in a browser: `http://localhost:3000`
* Install shapely and equation: Open a python console in blender and execute: `import pip; pip.main('install shapely Equation'.split())`
* Install "Extra curve" from "Get Extensions"
* Add "blendercam" script from "File Paths"
* Close the docker and relaunch it (i didn't find a way to reopen blender without closing the docker)
```
docker kill blender
docker run --rm --name blender -p 3000:3000 -p 3001:3001 -v $PWD:/blendercam -v ./blender_config:/config/ -e PUID=0 -e GUID=0 lscr.io/linuxserver/blender:latest
```

* Connect again with the browser to `http://localhost:3000`
* Enable blandercam addon
* Run "Object silhouette"

```
Error: Python: Traceback (most recent call last):
  File "/blendercam/scripts/addons/cam/curvecamtools.py", line 815, in execute
    bpy.ops.object.curve_remove_doubles()
  File "/blender/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/blendercam/scripts/addons/cam/curvecamtools.py", line 595, in execute
    bpy.ops.curve.remove_double(distance=0.00001)
  File "/blender/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.curve.remove_double" error, could not be found
Location: /blender/4.2/scripts/modules/bpy/ops.py:109
```

**Comment by ydnatag** [comment]
Found it, `Simplify curves+` extension is also needed. It is working now. I will let you know if 4.2 breaks another stuff.

Regards!

**Comment by pppalain** [comment]
there are a few other things the new version fixes.  Just made new pulls today.
