### ISSUE TITLE
[BUG] Cutout of an an open curve closes it using the cutting depth

### ISSUE THREAD

**Issue by opensourcecnc** [pppalain/blendercam#186]
**Describe the Bug**
When milling the profile of an open curve (the default bezier, for example) the cutter returns to the start position using the cutting depth, as if the curve was closed using a straight line.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Create a new bezier curve
2. Create a new cutout operation
3. Generate the toolpath

**Expected Behavior**
The cutter should be lifted to the safe height and either stop (if the job is done) or move back to start and mill next layer 

**System Information:**
 - OS: [Win 11]
 - Blender Version: [4.2.1]
 - Addon Version: [1.0.37]

**Comment by pppalain** [comment]
if curve is open strategy should be curve to path

**Comment by pppalain** [comment]
tried it and don't get that effect on profile strategy with an open curve
![image](https://github.com/user-attachments/assets/245bca5c-1507-497c-8e93-f3f60d7832ab)

**Comment by opensourcecnc** [comment]
Yes, but in this case you don't have the offset of the toolbit relative to the cut line. Maybe an additional field with the offset and a tick to change side would work? I use this scenario pretty often when milling only one side of a shape and having a way to set the offset when setting the operation would be awesome.

**Comment by pppalain** [comment]
no, you have to make an object silhouette offset and dialate open curve

**Comment by opensourcecnc** [comment]
I understand that it's not a bug, but I think it would be a nice feature.
Use case scenario: the stock for this shape are two blocks of wood glued together. I want to mill the outside of the top block, where it stays over the lower block.
I would have to somehow limit the operation to just that side, which I cannot for now either by using an ambient limiting curve shape or by using the profile on an open curve with an offset to accommodate the toolbit.

![Screenshot 2024-09-21 172916](https://github.com/user-attachments/assets/e628fda4-eac7-499f-9de8-e0778dff364e)

**Comment by pppalain** [comment]
how I would do an operation like that would be to get the curve for the top of the object in question.  silhouette offset to desired distance then manually edit the vertices you want to keep and delete the unwanted ones.  Sorry, don't know how to automate that one and not make it very difficult to use.
