### ISSUE TITLE
Issues with depth calculation for Curve_to_Path strategy

### ISSUE THREAD

**Issue by migo1001** [pppalain/blendercam#67]
Please check the following Blender file, which has three operations:
https://www6.zippyshare.com/v/7zs1O3JS/file.html

- **Op_Cutout** is a simple cutout operation. Layer depth is 1mm, Depth start is at 0, Depth End is at -1 cm, and the generated operation displays the expected behaviour.
- **Op_Curve_To_Path** is a curve to path operation. Layer depth is 1mm, Depth start is at 0, Depth End is at -1 cm. The generated operation is wrong: the cut would happen above the z plan.
- **Op_Curve_To_Path_Fixed** is a curve to path operation. Layer depth is 1mm, Depth start is at -0.5 cm, Depth End is at -1.5 cm. With those parameters, the generated cut would stay below the z plane. 

So there is a problem with those depth calculations: in order to have a normal cut below the z axis, one should only need to set the depth start at 0, and the depth end at -1 cm.

**Comment by SpectralVectors** [comment]
Closing this for now, given how old it is, and how much has changed in the code since then.
If it is still an issue, feel free to re-open.
Thanks!
