### ISSUE TITLE
check object types etc.

### ISSUE THREAD

**Issue by joemarshall** [pppalain/blendercam#78]
If e.g. you select a text object and forget to convert to curve, or select a curve for something expecting a mesh or vice-versa, bad things happen, ranging from blender crash, to python errors.

The python errors I'm more cool with I guess, but the blender crashes are not so good.

**Comment by pppalain** [comment]
can you give an example where that may be the case? what were you doing?

**Comment by joemarshall** [comment]
PR #79 fixes this. 

It's if you have a curve or a text object selected, and are using opencamlib. 

I fixed it. Also fixed the case where you select something totally stupid like a light, it gives a sensible exception now.

Oh and I made the opencamlib code support curves and text objects correctly which was a trivial change to a single if statement, because the stl conversion code calls get mesh internally.

**Comment by pppalain** [comment]
great I will close the issue then.  Nice that you raised the issue and was able to fix it yourself.  Bonus points for you in 2023... that's how it starts!
